### PR TITLE
Remove types.h, always use stdint.h

### LINKED ISSUE #90: types.h not found
As I've been having this `rs_search_for_block` crash problem ( #50 ) on 2.0.0 occasionally, I gave the master branch a shot. When I was compiling against the newly installed librsync, a compilation error pops out:

> /usr/local/include/librsync.h:40:19: fatal error: types.h: No such file or directory

I can see that `librsync.h` is including a `types.h`, but there's no sight of this file under `/usr/local/include`. Maybe there's one step missing in installation process to copy this file?

### PR DESCRIPTION
**Pull request by sourcefrog**
Fixes #90

### CODE REVIEW

File: src/librsync.h [hunk 1]
```diff
@@ -37,7 +37,7 @@
 #define _RSYNC_H
 
 #include <sys/types.h>
-#include "types.h"
+#include <stdint.h>
 #include "librsync-config.h"
```
Comment (dbaarda) [inline src/librsync.h]: Note that librsync-config.h includes only the typedef for rs_long_t and is built from librsync-config.h.cmake, using some  logic in CMakeLists.txt that is preceeded by a FIXME comment about how this is a bit ugly.

Now we have stdint.h we could also drop librsync-config.h and just define rs_long_t as intmax_t here.

There are arguments that off_t would be more appropriate (since it's a file offset, which is what off_t is for). However the standards are sufficiently fuzzy that there is also off64_t and loff_t, and which does what depends on things like defining "#define _FILE_OFFSET_BITS 64" or "#define _LARGEFILE64_SOURCE" and it's all compiler and platform dependent, so a mess. I think intmax_t is simple, encapsulates what we want, and should cause no problems.
